### ISSUE TITLE
internal error 

### ISSUE THREAD

**Issue by cowrycoin** [darkstarSH/redmine_contacts_helpdesk_gpg#6]
Unfortunately I got an error like:

```
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.
```

Production.log says:
```

NoMethodError (undefined method `delete' for nil:NilClass):
  plugins/redmine_contacts_helpdesk_gpg/lib/gpgkeys.rb:7:in `new'
  plugins/redmine_contacts_helpdesk_gpg/lib/gpgkeys.rb:7:in `initGPG'
  plugins/redmine_contacts_helpdesk_gpg/app/controllers/gpgkeys_controller.rb:11:in `initialize'
```

Setup is:

*Environment:*
  Redmine version                3.4.6.stable.17594
  Ruby version                   2.5.3-p105 (2018-10-18) [x86_64-linux]
  Rails version                  4.2.10
  Environment                    production
  Database adapter               Mysql2
*SCM:*
  Subversion                     1.7.14
  Darcs                          2.8.4
  Mercurial                      2.6.2
  Git                            2.16.5
  Filesystem                     
*Redmine plugins:*
  additionals                    2.0.15
  bestest_markdown_editor        1.1.0
  bestest_timer                  1.2.0
  redmine_agile                  1.4.7
  redmine_auto_resubmission      1.0.2
  redmine_checklists             3.1.11
  redmine_contacts               4.2.2
  redmine_contacts_helpdesk      4.0.0
  redmine_contacts_helpdesk_gpg  0.0.9
  redmine_contacts_invoices      4.1.6
  redmine_custom_css             0.1.7
  redmine_drawio                 0.8.2
  redmine_fetch_email_attachments 2.0.2
  redmine_finance                2.1.4
  redmine_issue_attachments      1.0.4
  redmine_issue_templates        0.2.0
  redmine_more_code              1.0.0
  redmine_people                 1.4.0
  redmine_preview_inline         1.0.2
  redmine_products               2.0.5
  redmine_reporter               1.0.0
  redmine_shortcuts              0.1.0
  redmine_telegram_global        0.1
  vault                          0.3.9

**Comment by darkstarSH** [comment]
hmm, that's where the HKP client is initialized.
That class is provided by mail-gpg.

So, which version of mail-gpg is installed? Execute "gem list mail-gpg".

Did you follow the installation instruction? (see "Install required GEMs")

**Comment by cowrycoin** [comment]
_$ gem list mail-gpg_
*** LOCAL GEMS ***

mail-gpg (0.4.0, 0.2.9)

And I had difficulties to install it with  `-- --use-system-libraries`

So I made just `gem install gpgme`
